defaults:
  - env: entity
  - learning: 
    - ppo-base
    - ppo-ued
  - misc: misc
  - env_size: m
  - eval: m
  - eval_env_size: m
  - ued: accel
  - train_levels: random
  - model: 
    - model-base
    - model-transformer
  - _self_

seed: 4